# Generated by Django 5.0 on 2024-02-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0001_initial'),
        ('core_user', '0002_user_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_liked',
            field=models.ManyToManyField(related_name='commented_by', to='core_comment.comment'),
        ),
    ]
